import { FaDownload, FaFileLines, FaTriangleExclamation, FaCircleCheck } from "react-icons/fa6";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import type { MockProject } from "@/data/lecturerData";
import { toast } from "sonner";

interface ProjectDetailsModalProps {
  project: MockProject | null;
  isOpen: boolean;
  onClose: () => void;
}

const ProjectDetailsModal = ({ project, isOpen, onClose }: ProjectDetailsModalProps) => {
  if (!project) return null;

  const getStatusColor = (status: MockProject["status"]) => {
    switch (status) {
      case "Low":
        return "bg-emerald-500/10 text-emerald-600 border-emerald-500/20";
      case "Medium":
        return "bg-amber-500/10 text-amber-600 border-amber-500/20";
      case "High":
        return "bg-rose-500/10 text-rose-600 border-rose-500/20";
      default:
        return "bg-muted text-muted-foreground";
    }
  };

  const handleDownload = () => {
    const reportText = `
ANTI-PLAGIARISM SYSTEM - ACADEMIC RESEARCH PLAGIARISM REPORT
============================================================
PROJECT ID: ${project.id}
PROJECT TITLE: ${project.title}
SUBMITTED BY: ${project.studentName} (ID: ${project.studentId})
DATE CHECKED: ${project.dateSubmitted}
WORDS ANALYZED: ${project.wordCount}
SIMILARITY PERCENTAGE: ${project.similarityPercent}%
PLAGIARISM STATUS: ${project.status.toUpperCase()}

MATCHED SOURCES METRICS:
------------------------
${project.matchedDocs.map((doc, idx) => `
Source [${idx + 1}]: ${doc.source}
Match Score: ${doc.similarity}%
Snippet: "${doc.matchedText}"
`).join("\n")}

============================================================
Generated by Anti-Plagiarism System Lecturer Portal.
`;

    const blob = new Blob([reportText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${project.title.replace(/\s+/g, "_")}_Plagiarism_Report.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    toast.success("Plagiarism report downloaded successfully.");
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-2xl rounded-2xl border border-border bg-card p-6 shadow-xl animate-fade-in md:p-8">
        <DialogHeader className="space-y-3">
          <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
            <Badge variant="outline" className={`w-fit rounded-lg px-2.5 py-0.5 font-semibold ${getStatusColor(project.status)}`}>
              {project.status} Plagiarism Level
            </Badge>
            <span className="text-xs text-muted-foreground">ID: {project.id}</span>
          </div>
          <DialogTitle className="font-heading text-xl font-bold leading-snug text-foreground sm:text-2xl">
            {project.title}
          </DialogTitle>
          <DialogDescription className="text-sm text-muted-foreground">
            Academic Research Project analysis details and source matches.
          </DialogDescription>
        </DialogHeader>

        <div className="mt-6 grid gap-6 md:grid-cols-2">
          {/* Left panel: Info */}
          <div className="space-y-4 rounded-xl bg-muted/30 p-5 border border-border/40">
            <h4 className="font-heading text-sm font-bold text-foreground">Project Information</h4>
            <div className="space-y-3.5 text-sm">
              <div className="flex justify-between border-b border-border/50 pb-2">
                <span className="text-muted-foreground">Student Name</span>
                <span className="font-semibold text-foreground">{project.studentName}</span>
              </div>
              <div className="flex justify-between border-b border-border/50 pb-2">
                <span className="text-muted-foreground">Student ID</span>
                <span className="font-medium text-foreground">{project.studentId}</span>
              </div>
              <div className="flex justify-between border-b border-border/50 pb-2">
                <span className="text-muted-foreground">Date Uploaded</span>
                <span className="font-medium text-foreground">{project.uploadedDate}</span>
              </div>
              <div className="flex justify-between border-b border-border/50 pb-2">
                <span className="text-muted-foreground">Word Count</span>
                <span className="font-medium text-foreground">{project.wordCount.toLocaleString()} words</span>
              </div>
              <div className="flex justify-between items-center pt-1">
                <span className="text-muted-foreground">Similarity Score</span>
                <span className={`text-lg font-bold ${project.similarityPercent >= 50 ? "text-rose-600" : project.similarityPercent >= 21 ? "text-amber-500" : "text-emerald-600"}`}>
                  {project.similarityPercent}%
                </span>
              </div>
            </div>
          </div>

          {/* Right panel: Plagiarism Details Gauge */}
          <div className="flex flex-col items-center justify-center rounded-xl border border-border/40 p-5 bg-card shadow-sm">
            <div className="relative flex h-28 w-28 items-center justify-center rounded-full border-4 border-muted">
              {/* Simple CSS gauge circle */}
              <div
                className="absolute inset-0 rounded-full border-4 border-transparent"
                style={{
                  borderTopColor: project.similarityPercent >= 50 ? "rgb(239, 68, 68)" : project.similarityPercent >= 21 ? "rgb(245, 158, 11)" : "rgb(16, 185, 129)",
                  borderRightColor: project.similarityPercent >= 50 ? "rgb(239, 68, 68)" : project.similarityPercent >= 21 ? "rgb(245, 158, 11)" : "transparent",
                  transform: `rotate(${Math.min(project.similarityPercent * 3.6, 360)}deg)`,
                  transition: "transform 1s ease-out",
                }}
              />
              <div className="text-center z-10">
                <span className="text-2xl font-extrabold text-foreground">{project.similarityPercent}%</span>
                <p className="text-[10px] uppercase font-bold text-muted-foreground tracking-wider">Similarity</p>
              </div>
            </div>
            <div className="mt-4 flex items-center gap-1.5 text-xs font-medium">
              {project.similarityPercent >= 50 ? (
                <>
                  <FaTriangleExclamation className="text-rose-500 h-4 w-4" />
                  <span className="text-rose-600">Requires Academic Action</span>
                </>
              ) : (
                <>
                  <FaCircleCheck className="text-emerald-500 h-4 w-4" />
                  <span className="text-emerald-600">Within Acceptable Threshold</span>
                </>
              )}
            </div>
          </div>
        </div>

        {/* Matched Documents list */}
        <div className="mt-6 space-y-3">
          <div className="flex items-center gap-2">
            <FaFileLines className="h-4 w-4 text-blue-500" />
            <h4 className="font-heading text-sm font-bold text-foreground">Matched Sources ({project.matchedDocs.length})</h4>
          </div>
          <ScrollArea className="h-40 rounded-xl border border-border/80 p-3 bg-muted/10">
            {project.matchedDocs.length === 0 ? (
              <p className="text-xs text-muted-foreground p-4 text-center">No matching source databases detected.</p>
            ) : (
              <div className="space-y-3">
                {project.matchedDocs.map((doc, idx) => (
                  <div key={idx} className="rounded-lg border border-border/50 bg-card p-3 shadow-xs">
                    <div className="flex items-center justify-between text-xs">
                      <span className="font-bold text-foreground text-blue-600 hover:underline cursor-pointer">{doc.source}</span>
                      <span className="font-bold text-rose-500">{doc.similarity}% match</span>
                    </div>
                    <p className="mt-2 text-xs italic text-muted-foreground leading-relaxed bg-muted/30 p-2 rounded border border-border/20">
                      "{doc.matchedText}"
                    </p>
                  </div>
                ))}
              </div>
            )}
          </ScrollArea>
        </div>

        {/* Action Buttons */}
        <div className="mt-6 flex flex-col gap-2 sm:flex-row sm:justify-end">
          <Button variant="ghost" onClick={onClose} className="rounded-xl border border-border">
            Close Panel
          </Button>
          <Button onClick={handleDownload} className="gap-2 bg-gradient-to-r from-blue-600 to-indigo-600 text-white shadow-md hover:from-blue-700 hover:to-indigo-700 rounded-xl">
            <FaDownload className="h-3.5 w-3.5" />
            Download Plagiarism Report
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default ProjectDetailsModal;
